#!/usr/bin/env bash

die() {
  echo "$*" >&2
  exit 2
}

[[ "$#" -lt 2 ]] || die "Two arguments required <source> <target>"

source_nfs_url="$1"
target_nfs_url="$2"

src=/mnt/source
trg=/mnt/target

set -x
mkdir -p "$src" "$trg"
mount -t nfs4 -o nfsvers=4.1,ro "$source_nfs_url" "$src"
mount -t nfs4 -o nfsvers=4.1,rw "$target_nfs_url" "$trg"

#find "$src" "$trg" f

echo $source
echo $target
