#!/usr/bin/env bash

. /common

RETAIN="$((${RETAIN:-5}-1))"

cd "$trg"

( set -x; rm -rf "$retain"; )

printf "%s\n" */ |
  sed 's|/$||'   |
  grep -v '^0$'  |
  sort -gr       |
  while read d; do ( set -x; mv "$d" "$((d+1))"; ); done

( set -x; cp -al "$trg/0" "$trg/1"; )

