#!/usr/bin/env bash

. /common

RETAIN="$((${RETAIN:-5}-1))"

cd "$trg"

( set -x; rm -rf "$RETAIN"; )

printf "%s\n" */ |
  sed 's|/$||' |
  egrep '^[1-9][[:digit:]]*$' |
  sort -gr |
  while read d; do ( set -x; mv "$d" "$((d+1))"; ); done

( set -x; cp -al "$trg/0" "$trg/1"; )

