#!/usr/bin/env bash

. /common

RETAIN="$${RETAIN:-5}"
RETAIN_STR="$(for ((i=0;i<RETAIN;i++)); do echo -n O; done)"

cd "$trg"

( set -x; rm -rf *%$RETAIN_STR*; )

printf "%s\n" */ |
  sed 's|/$||' |
  egrep "$namesep"'OO+$' |
  sort -t"%" -k2 -r |
  while read d; do ( set -x; mv "$d" "${d}O"; ); done

(
  set -x;
  cp -al "$latest_trg" "${latest_trg}O"
  rsync -a --delete --include='*/' --exclude='*' "$src/" "$latest_trg"
)
