#!/usr/bin/env bash

. /common "$1" "$2"

numClients="$1"
clientNum="$2"

echo "numClients: $numClients, clientNum: $clientNum"

set -e

cd "$src"
for myContent in $(ls -A . | awk "NR%$numClients==$clientNum"); do
  ( set -x; rsync -s -ah --stats --delete --numeric-ids "$myContent" "$trg/0/"; )
done
